version: 2.1
orbs:
    git-shallow-clone: guitarrapc/git-shallow-clone@2.0.3
  
executors:
    base:
        docker:
            - image: cimg/base:2020.01

jobs:
    build:
        executor: base
        steps:
        - git-shallow-clone/checkout
        - run:
            name: Test git in bash script
            command: chmod +x .circleci/circle_test.sh && .circleci/circle_test.sh
        - run:
            name: Test git in circleci command
            environment:
                PACKAGE_PATH: "./packages"       
            command: |
                echo -e $(git rev-list -1 develop..$CIRCLE_SHA1 -- ${PACKAGE_PATH#./} | cat)
                echo -e $(git rev-list -1 develop..$CIRCLE_SHA1 | cat)
                echo -e $(git rev-list develop..$CIRCLE_SHA1 | cat)
                git rev-list --count develop..$CIRCLE_SHA1
                git rev-list --count HEAD

workflows:
    version: 2
    ci:
        jobs:
        - build