version: 2.1

executors:
    base:
        docker:
            - image: cimg/base:2020.01

jobs:
    build:
        executor: base
        steps:
        - checkout
        - run:
            name: Test git in bash script
            command: chmod +x .circleci/circle_test.sh && .circleci/circle_test.sh
        - run:
            name: Test git in circleci command
            environment:
                PACKAGE_PATH: "./packages"       
            command: |
                DEVELOP_SHA1=$(git rev-parse origin/develop)
                echo -e " DEVELOP_SHA1 $DEVELOP_SHA1"
                echo -e "latest commit in package path since develop"
                git rev-list -1 $DEVELOP_SHA1..$CIRCLE_SHA1 -- ${PACKAGE_PATH#./}
                echo -e "latest commit since develop"
                git rev-list -1 $DEVELOP_SHA1..$CIRCLE_SHA1
                echo -e "all commits since develop"
                git rev-list $DEVELOP_SHA1..$CIRCLE_SHA1
                echo -e "count all commits since develop"
                git rev-list --count $DEVELOP_SHA1..$CIRCLE_SHA1
                echo -e "count all commits"
                git rev-list --count HEAD

workflows:
    version: 2
    ci:
        jobs:
        - build