version: 2.1

executors:
    base:
        docker:
            - image: cimg/base:2020.01

jobs:
    build:
        executor: base
        steps:
        - checkout
        - run:
            name: Test git in bash script
            command: chmod +x .circleci/circle_test.sh && .circleci/circle_test.sh
        - run:
            name: Test git in circleci command
            environment:
                PACKAGE_PATH: "./packages"       
            command: |
                echo -e $(git rev-list -1 $CIRCLE_SHA1 ^develop -- ${PACKAGE_PATH#./} | cat)
                echo -e $(git rev-list -1 $CIRCLE_SHA1 ^develop | cat)
                echo -e $(git rev-list $CIRCLE_SHA1 ^develop | cat)
                git rev-list --count $CIRCLE_SHA1 ^develop
                git rev-list --count HEAD

workflows:
    version: 2
    ci:
        jobs:
        - build